//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicasaUpload.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicasaUpload.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.mlsteeves.com/picasapublisher/.
        /// </summary>
        internal static string BASE_URL {
            get {
                return ResourceManager.GetString("BASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current_version.txt.
        /// </summary>
        internal static string CURRENT_VERSION_URL {
            get {
                return ResourceManager.GetString("CURRENT_VERSION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.html.
        /// </summary>
        internal static string DONATE_URL {
            get {
                return ResourceManager.GetString("DONATE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.html.
        /// </summary>
        internal static string FEEDBACK_URL {
            get {
                return ResourceManager.GetString("FEEDBACK_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00FF00.
        /// </summary>
        internal static string LATEST_VERSION_COLOR {
            get {
                return ResourceManager.GetString("LATEST_VERSION_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        internal static string LATEST_VERSION_TEXT {
            get {
                return ResourceManager.GetString("LATEST_VERSION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF6361.
        /// </summary>
        internal static string NEED_TO_UPGRADE_COLOR {
            get {
                return ResourceManager.GetString("NEED_TO_UPGRADE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version.  Click to download..
        /// </summary>
        internal static string NEED_TO_UPGRADE_TEXT {
            get {
                return ResourceManager.GetString("NEED_TO_UPGRADE_TEXT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewAlbumImage {
            get {
                object obj = ResourceManager.GetObject("NewAlbumImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.html.
        /// </summary>
        internal static string UPGRADE_URL {
            get {
                return ResourceManager.GetString("UPGRADE_URL", resourceCulture);
            }
        }
    }
}
