//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicasaUpload.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicasaUpload.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 http://www.mlsteeves.com/picasapublisher/ 的當地語系化字串。
        /// </summary>
        internal static string BASE_URL {
            get {
                return ResourceManager.GetString("BASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 check_update/ 的當地語系化字串。
        /// </summary>
        internal static string CURRENT_VERSION_URL {
            get {
                return ResourceManager.GetString("CURRENT_VERSION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 donate.html 的當地語系化字串。
        /// </summary>
        internal static string DONATE_URL {
            get {
                return ResourceManager.GetString("DONATE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 feedback.html 的當地語系化字串。
        /// </summary>
        internal static string FEEDBACK_URL {
            get {
                return ResourceManager.GetString("FEEDBACK_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 #00FF00 的當地語系化字串。
        /// </summary>
        internal static string LATEST_VERSION_COLOR {
            get {
                return ResourceManager.GetString("LATEST_VERSION_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have the latest version 的當地語系化字串。
        /// </summary>
        internal static string LATEST_VERSION_TEXT {
            get {
                return ResourceManager.GetString("LATEST_VERSION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 #FF6361 的當地語系化字串。
        /// </summary>
        internal static string NEED_TO_UPGRADE_COLOR {
            get {
                return ResourceManager.GetString("NEED_TO_UPGRADE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is a new version.  Click to download. 的當地語系化字串。
        /// </summary>
        internal static string NEED_TO_UPGRADE_TEXT {
            get {
                return ResourceManager.GetString("NEED_TO_UPGRADE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap NewAlbumImage {
            get {
                object obj = ResourceManager.GetObject("NewAlbumImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 download.html 的當地語系化字串。
        /// </summary>
        internal static string UPGRADE_URL {
            get {
                return ResourceManager.GetString("UPGRADE_URL", resourceCulture);
            }
        }
    }
}
