//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace PicasaUpload.UI {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("SelectAlbumDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class SelectAlbumDataSet : global::System.Data.DataSet {
        
        private SelectAlbumTableDataTable tableSelectAlbumTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SelectAlbumDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected SelectAlbumDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["SelectAlbumTable"] != null)) {
                    base.Tables.Add(new SelectAlbumTableDataTable(ds.Tables["SelectAlbumTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SelectAlbumTableDataTable SelectAlbumTable {
            get {
                return this.tableSelectAlbumTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            SelectAlbumDataSet cln = ((SelectAlbumDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SelectAlbumTable"] != null)) {
                    base.Tables.Add(new SelectAlbumTableDataTable(ds.Tables["SelectAlbumTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableSelectAlbumTable = ((SelectAlbumTableDataTable)(base.Tables["SelectAlbumTable"]));
            if ((initTable == true)) {
                if ((this.tableSelectAlbumTable != null)) {
                    this.tableSelectAlbumTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "SelectAlbumDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/SelectAlbumDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSelectAlbumTable = new SelectAlbumTableDataTable();
            base.Tables.Add(this.tableSelectAlbumTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeSelectAlbumTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            SelectAlbumDataSet ds = new SelectAlbumDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void SelectAlbumTableRowChangeEventHandler(object sender, SelectAlbumTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SelectAlbumTableDataTable : global::System.Data.TypedTableBase<SelectAlbumTableRow> {
            
            private global::System.Data.DataColumn columnRememberUsername;
            
            private global::System.Data.DataColumn columnUsername;
            
            private global::System.Data.DataColumn columnAuthenticationToken;
            
            private global::System.Data.DataColumn columnSelectedAlbumId;
            
            private global::System.Data.DataColumn columnLastCheckForUpdate;
            
            private global::System.Data.DataColumn columnLastUpdateValue;
            
            private global::System.Data.DataColumn columnSelectedAlbumEntry;
            
            private global::System.Data.DataColumn columnPhotoSize;
            
            private global::System.Data.DataColumn columnUseDefaultAlbum;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SelectAlbumTableDataTable() {
                this.TableName = "SelectAlbumTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SelectAlbumTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected SelectAlbumTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RememberUsernameColumn {
                get {
                    return this.columnRememberUsername;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UsernameColumn {
                get {
                    return this.columnUsername;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AuthenticationTokenColumn {
                get {
                    return this.columnAuthenticationToken;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SelectedAlbumIdColumn {
                get {
                    return this.columnSelectedAlbumId;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LastCheckForUpdateColumn {
                get {
                    return this.columnLastCheckForUpdate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LastUpdateValueColumn {
                get {
                    return this.columnLastUpdateValue;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SelectedAlbumEntryColumn {
                get {
                    return this.columnSelectedAlbumEntry;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PhotoSizeColumn {
                get {
                    return this.columnPhotoSize;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UseDefaultAlbumColumn {
                get {
                    return this.columnUseDefaultAlbum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SelectAlbumTableRow this[int index] {
                get {
                    return ((SelectAlbumTableRow)(this.Rows[index]));
                }
            }
            
            public event SelectAlbumTableRowChangeEventHandler SelectAlbumTableRowChanging;
            
            public event SelectAlbumTableRowChangeEventHandler SelectAlbumTableRowChanged;
            
            public event SelectAlbumTableRowChangeEventHandler SelectAlbumTableRowDeleting;
            
            public event SelectAlbumTableRowChangeEventHandler SelectAlbumTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddSelectAlbumTableRow(SelectAlbumTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SelectAlbumTableRow AddSelectAlbumTableRow(bool RememberUsername, string Username, string AuthenticationToken, string SelectedAlbumId, System.DateTime LastCheckForUpdate, bool LastUpdateValue, Google.GData.Photos.PicasaEntry SelectedAlbumEntry, int PhotoSize, bool UseDefaultAlbum) {
                SelectAlbumTableRow rowSelectAlbumTableRow = ((SelectAlbumTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        RememberUsername,
                        Username,
                        AuthenticationToken,
                        SelectedAlbumId,
                        LastCheckForUpdate,
                        LastUpdateValue,
                        SelectedAlbumEntry,
                        PhotoSize,
                        UseDefaultAlbum};
                rowSelectAlbumTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowSelectAlbumTableRow);
                return rowSelectAlbumTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                SelectAlbumTableDataTable cln = ((SelectAlbumTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new SelectAlbumTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnRememberUsername = base.Columns["RememberUsername"];
                this.columnUsername = base.Columns["Username"];
                this.columnAuthenticationToken = base.Columns["AuthenticationToken"];
                this.columnSelectedAlbumId = base.Columns["SelectedAlbumId"];
                this.columnLastCheckForUpdate = base.Columns["LastCheckForUpdate"];
                this.columnLastUpdateValue = base.Columns["LastUpdateValue"];
                this.columnSelectedAlbumEntry = base.Columns["SelectedAlbumEntry"];
                this.columnPhotoSize = base.Columns["PhotoSize"];
                this.columnUseDefaultAlbum = base.Columns["UseDefaultAlbum"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnRememberUsername = new global::System.Data.DataColumn("RememberUsername", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRememberUsername);
                this.columnUsername = new global::System.Data.DataColumn("Username", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUsername);
                this.columnAuthenticationToken = new global::System.Data.DataColumn("AuthenticationToken", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAuthenticationToken);
                this.columnSelectedAlbumId = new global::System.Data.DataColumn("SelectedAlbumId", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSelectedAlbumId);
                this.columnLastCheckForUpdate = new global::System.Data.DataColumn("LastCheckForUpdate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastCheckForUpdate);
                this.columnLastUpdateValue = new global::System.Data.DataColumn("LastUpdateValue", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastUpdateValue);
                this.columnSelectedAlbumEntry = new global::System.Data.DataColumn("SelectedAlbumEntry", typeof(global::Google.GData.Photos.PicasaEntry), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSelectedAlbumEntry);
                this.columnPhotoSize = new global::System.Data.DataColumn("PhotoSize", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPhotoSize);
                this.columnUseDefaultAlbum = new global::System.Data.DataColumn("UseDefaultAlbum", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUseDefaultAlbum);
                this.columnPhotoSize.AllowDBNull = false;
                this.columnPhotoSize.DefaultValue = ((int)(0));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SelectAlbumTableRow NewSelectAlbumTableRow() {
                return ((SelectAlbumTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new SelectAlbumTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(SelectAlbumTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SelectAlbumTableRowChanged != null)) {
                    this.SelectAlbumTableRowChanged(this, new SelectAlbumTableRowChangeEvent(((SelectAlbumTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SelectAlbumTableRowChanging != null)) {
                    this.SelectAlbumTableRowChanging(this, new SelectAlbumTableRowChangeEvent(((SelectAlbumTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SelectAlbumTableRowDeleted != null)) {
                    this.SelectAlbumTableRowDeleted(this, new SelectAlbumTableRowChangeEvent(((SelectAlbumTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SelectAlbumTableRowDeleting != null)) {
                    this.SelectAlbumTableRowDeleting(this, new SelectAlbumTableRowChangeEvent(((SelectAlbumTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveSelectAlbumTableRow(SelectAlbumTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SelectAlbumDataSet ds = new SelectAlbumDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SelectAlbumTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class SelectAlbumTableRow : global::System.Data.DataRow {
            
            private SelectAlbumTableDataTable tableSelectAlbumTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SelectAlbumTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSelectAlbumTable = ((SelectAlbumTableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool RememberUsername {
                get {
                    try {
                        return ((bool)(this[this.tableSelectAlbumTable.RememberUsernameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RememberUsername\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.RememberUsernameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Username {
                get {
                    try {
                        return ((string)(this[this.tableSelectAlbumTable.UsernameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Username\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.UsernameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AuthenticationToken {
                get {
                    try {
                        return ((string)(this[this.tableSelectAlbumTable.AuthenticationTokenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AuthenticationToken\' in table \'SelectAlbumTable\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.AuthenticationTokenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SelectedAlbumId {
                get {
                    try {
                        return ((string)(this[this.tableSelectAlbumTable.SelectedAlbumIdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SelectedAlbumId\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.SelectedAlbumIdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime LastCheckForUpdate {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableSelectAlbumTable.LastCheckForUpdateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LastCheckForUpdate\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.LastCheckForUpdateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool LastUpdateValue {
                get {
                    try {
                        return ((bool)(this[this.tableSelectAlbumTable.LastUpdateValueColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LastUpdateValue\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.LastUpdateValueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Google.GData.Photos.PicasaEntry SelectedAlbumEntry {
                get {
                    try {
                        return ((global::Google.GData.Photos.PicasaEntry)(this[this.tableSelectAlbumTable.SelectedAlbumEntryColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SelectedAlbumEntry\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.SelectedAlbumEntryColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int PhotoSize {
                get {
                    return ((int)(this[this.tableSelectAlbumTable.PhotoSizeColumn]));
                }
                set {
                    this[this.tableSelectAlbumTable.PhotoSizeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool UseDefaultAlbum {
                get {
                    try {
                        return ((bool)(this[this.tableSelectAlbumTable.UseDefaultAlbumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UseDefaultAlbum\' in table \'SelectAlbumTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableSelectAlbumTable.UseDefaultAlbumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRememberUsernameNull() {
                return this.IsNull(this.tableSelectAlbumTable.RememberUsernameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRememberUsernameNull() {
                this[this.tableSelectAlbumTable.RememberUsernameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUsernameNull() {
                return this.IsNull(this.tableSelectAlbumTable.UsernameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUsernameNull() {
                this[this.tableSelectAlbumTable.UsernameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAuthenticationTokenNull() {
                return this.IsNull(this.tableSelectAlbumTable.AuthenticationTokenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAuthenticationTokenNull() {
                this[this.tableSelectAlbumTable.AuthenticationTokenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSelectedAlbumIdNull() {
                return this.IsNull(this.tableSelectAlbumTable.SelectedAlbumIdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSelectedAlbumIdNull() {
                this[this.tableSelectAlbumTable.SelectedAlbumIdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLastCheckForUpdateNull() {
                return this.IsNull(this.tableSelectAlbumTable.LastCheckForUpdateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLastCheckForUpdateNull() {
                this[this.tableSelectAlbumTable.LastCheckForUpdateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLastUpdateValueNull() {
                return this.IsNull(this.tableSelectAlbumTable.LastUpdateValueColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLastUpdateValueNull() {
                this[this.tableSelectAlbumTable.LastUpdateValueColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSelectedAlbumEntryNull() {
                return this.IsNull(this.tableSelectAlbumTable.SelectedAlbumEntryColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSelectedAlbumEntryNull() {
                this[this.tableSelectAlbumTable.SelectedAlbumEntryColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUseDefaultAlbumNull() {
                return this.IsNull(this.tableSelectAlbumTable.UseDefaultAlbumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUseDefaultAlbumNull() {
                this[this.tableSelectAlbumTable.UseDefaultAlbumColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class SelectAlbumTableRowChangeEvent : global::System.EventArgs {
            
            private SelectAlbumTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SelectAlbumTableRowChangeEvent(SelectAlbumTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SelectAlbumTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591